=== RafaelicoBR/Portugol/Projetos/Portugol-Studio/src/br/univali/ps/ui/acoes/actions.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.univali.br/portugol/ide/actions.xsd"
    elementFormDefault="qualified"
    xmlns="http://www.univali.br/portugol/ide/actions.xsd"
    xmlns:mstns="http://www.univali.br/portugol/ide/actions.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:element name="actions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="action" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="icon" type="iconName" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>      
    </xs:complexType>    
  </xs:element>

  <xs:simpleType name="iconName" id="iconName">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z0-9_.-]+\.(png|ico)"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== RafaelicoBR/Portugol/Codigo-Fonte/Portugol-Studio/src/br/univali/ps/ui/acoes/actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : newXMLDocument.xml
    Created on : 3 de Agosto de 2010, 21:10
    Author     : Fillipi Pelz
    Description:
        Purpose of the document follows.
-->

<actions  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.univali.br/portugol/ide/actions.xsd'
   xsi:schemaLocation='http://www.univali.br/portugol/ide/actions.xsd actions.xsd'>
    <action id="AcaoNovoArquivo">
        <title>Novo</title>
        <icon>page_white_add.png</icon>
    </action>
    <action id="AcaoAbrirArquivo">
        <title>Abrir...</title>
        <icon>folder_open.png</icon>
    </action>
    <action id="AcaoSalvarArquivo">
        <title>Salvar...</title>
        <icon>disk.png</icon>
    </action>
    <action id="AcaoSalvarComo">
        <title>Salvar Como...</title>
        <icon>save_as.png</icon>
    </action>
    <action id="AcaoDesfazer">
        <title>Desfazer</title>
        <icon>arrow_undo.png</icon>
    </action>
    <action id="AcaoRefazer">
        <title>Refazer</title>
        <icon>arrow_redo.png</icon>
    </action>
    <action id="AcaoCopiar">
        <title>Copiar</title>
        <icon>page_white_copy.png</icon>
    </action>
    <action id="AcaoColar">
        <title>Colar</title>
        <icon>page_white_paste.png</icon>
    </action>
    <action id="AcaoRecortar">
        <title>Recortar</title>
        <icon>cut_red.png</icon>
    </action>
</actions>
